FROM eclipse-temurin:17-jdk-jammy AS build
WORKDIR /app
COPY . .
ARG SERVICE_MODULE
RUN ./gradlew --no-daemon ${SERVICE_MODULE}:bootJar -x test

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
ARG JAR_FILE
COPY --from=build /app/${JAR_FILE} /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
