import argparse
import csv
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def build_values(users):
    return ",\n".join(
        f"        ({sql_literal(email)}, {sql_literal(name)})"
        for email, name in users
    )


def main():
    parser = argparse.ArgumentParser(description="Generate Locust users.csv and PostgreSQL seed_users.sql")
    parser.add_argument("--count", type=int, default=1000, help="number of load-test users")
    parser.add_argument("--email-prefix", default="loadtest", help="email local-part prefix")
    parser.add_argument("--domain", default="example.com", help="email domain")
    parser.add_argument("--password", default="Password123!", help="plain password written to users.csv")
    parser.add_argument("--template-email", default="p6j6w6@naver.com", help="existing DB user whose BCrypt password hash will be copied")
    parser.add_argument("--password-hash", default=None, help="BCrypt password hash to write directly instead of copying from template user")
    parser.add_argument("--cash", type=int, default=10000000, help="cash_balance for generated accounts")
    parser.add_argument("--stock-code", default="HYU-MOTOR", help="optional stock_code to give seller users")
    parser.add_argument("--stock-quantity", type=int, default=0, help="optional stock quantity to give seller users")
    parser.add_argument("--seller-count", type=int, default=None, help="number of generated users that can sell; defaults to all users when stock quantity is positive")
    args = parser.parse_args()

    if args.count <= 0:
        raise SystemExit("--count must be positive")
    if args.stock_quantity < 0:
        raise SystemExit("--stock-quantity must be zero or positive")

    seller_count = args.seller_count
    if seller_count is None:
        seller_count = args.count if args.stock_quantity > 0 else 0
    if seller_count < 0 or seller_count > args.count:
        raise SystemExit("--seller-count must be between 0 and --count")

    users = []
    for index in range(1, args.count + 1):
        suffix = str(index).zfill(6)
        email = f"{args.email_prefix}{suffix}@{args.domain}"
        name = f"loadtest{suffix}"
        users.append((email, name))

    users_csv = BASE_DIR / "users.csv"
    with users_csv.open("w", newline="", encoding="utf-8") as file:
        writer = csv.writer(file)
        writer.writerow(["email", "password", "canSell"])
        for email, _ in users:
            writer.writerow([email, args.password, "true"])

    values_sql = build_values(users)
    stock_sql = ""
    if args.stock_quantity > 0 and seller_count > 0:
        seller_values_sql = build_values(users[:seller_count])
        stock_sql = f"""

WITH seller_users(email, name) AS (
    VALUES
{seller_values_sql}
)
INSERT INTO user_stocks (user_id, stock_code, quantity, locked_quantity, average_cost, created_at, updated_at)
SELECT u.user_id, {sql_literal(args.stock_code)}, {args.stock_quantity}, 0, s.base_price, NOW(), NOW()
FROM seller_users su
JOIN users u ON u.email = su.email
JOIN stocks s ON s.stock_code = {sql_literal(args.stock_code)}
ON CONFLICT (user_id, stock_code)
DO UPDATE SET
    quantity = EXCLUDED.quantity,
    locked_quantity = 0,
    average_cost = EXCLUDED.average_cost,
    updated_at = NOW();"""

    if args.password_hash:
        password_source_sql = f"SELECT {sql_literal(args.password_hash)} AS password"
        template_check_sql = ""
        password_comment = "-- This writes the supplied BCrypt password hash directly."
    else:
        password_source_sql = f"""SELECT password
    FROM users
    WHERE email = {sql_literal(args.template_email)}"""
        template_check_sql = f"""
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM users WHERE email = {sql_literal(args.template_email)}) THEN
        RAISE EXCEPTION 'Template user not found: {args.template_email}';
    END IF;
END $$;
"""
        password_comment = "-- This copies the BCrypt password hash from an existing template user."

    seed_sql = f"""-- Generated by loadtest/generate_users.py
{password_comment}
-- Plain password for Locust is stored in users.csv.

BEGIN;
{template_check_sql}
WITH password_source AS (
    {password_source_sql}
), seed_users(email, name) AS (
    VALUES
{values_sql}
), upserted_users AS (
    INSERT INTO users (email, password, name, created_at, updated_at)
    SELECT seed_users.email, password_source.password, seed_users.name, NOW(), NOW()
    FROM seed_users
    CROSS JOIN password_source
    ON CONFLICT (email)
    DO UPDATE SET
        password = EXCLUDED.password,
        name = EXCLUDED.name,
        updated_at = NOW()
    RETURNING user_id
)
INSERT INTO accounts (user_id, cash_balance, locked_cash, created_at, updated_at)
SELECT user_id, {args.cash}, 0, NOW(), NOW()
FROM upserted_users
ON CONFLICT (user_id)
DO UPDATE SET
    cash_balance = EXCLUDED.cash_balance,
    locked_cash = 0,
    updated_at = NOW();{stock_sql}

COMMIT;
"""
    (BASE_DIR / "seed_users.sql").write_text(seed_sql, encoding="utf-8")

    print(f"Generated {users_csv}")
    print(f"Generated {BASE_DIR / 'seed_users.sql'}")
    print(f"Users: {args.count}")
    print(f"Seller users: {args.count}")


if __name__ == "__main__":
    main()
